import { adaptGarmentMetadata } from '../garmentMetadataAdapter';
import { calculateBoneRotations } from '../skeletalRetargeter';
import type { GarmentMetadata, GarmentFitProfileV2 } from '../../types/garment';

const mockFallback = (): GarmentMetadata => ({
  id: 'fallback-id',
  category: 'shirt',
  calibrationVersion: '1.0.0',
  ingestionStatus: 'DEMO_RIG',
  anatomicalAnchorOffset: { x: 0, y: 0.5, z: 0 },
  anchorConfidence: 'inferred',
  anchorType: 'SHOULDER_CENTER',
  restPoseMetricWidth: 0.35,
  boneMap: {},
  restPose: 'A_POSE',
});

describe('Cross-Repository Garment Fit Profile V2 Contract', () => {
  // 1. Admin-authored Pants V2 raw DB JSON payload (as generated by Admin garmentIngestor)
  const adminPantsV2Payload = {
    id: 'pants-product-123',
    category: 'pants',
    calibration_version: '2.0.0',
    garment_fit_profile_version: 2,
    ingestion_status: 'AR_READY',
    anchor_type: 'WAIST',
    anchor_confidence: 'detected',
    rest_pose_metric_width: 0.38,
    anatomical_anchor_offset: { x: 0, y: 0.95, z: 0 },
    bone_map: {
      mixamorigHips: 'Hips',
      mixamorigLeftUpLeg: 'LeftUpLeg',
      mixamorigRightUpLeg: 'RightUpLeg',
      mixamorigLeftLeg: 'LeftLeg',
      mixamorigRightLeg: 'RightLeg',
    },
    fit_profile_v2: {
      version: 2,
      region: 'lower',
      category: 'pants',
      rootAnchor: {
        type: 'WAIST',
        offset: { x: 0, y: 0.95, z: 0 },
        inferredFrom: 'mesh_bounds',
      },
      skeletonProfile: {
        requiredBones: ['Hips', 'LeftUpLeg', 'RightUpLeg', 'LeftLeg', 'RightLeg'],
        optionalBones: ['LeftFoot', 'RightFoot', 'Spine'],
        unusedBones: ['LeftArm', 'RightArm', 'LeftForeArm', 'RightForeArm'],
      },
      boneMap: {
        mixamorigHips: 'Hips',
        mixamorigLeftUpLeg: 'LeftUpLeg',
        mixamorigRightUpLeg: 'RightUpLeg',
        mixamorigLeftLeg: 'LeftLeg',
        mixamorigRightLeg: 'RightLeg',
      },
      controlPoints: {
        waistCenter: { x: 0, y: 0.95, z: 0 },
        leftWaistEdge: { x: -0.19, y: 0.95, z: 0 },
        rightWaistEdge: { x: 0.19, y: 0.95, z: 0 },
        leftHipRegion: { x: -0.21, y: 0.85, z: 0 },
        rightHipRegion: { x: 0.21, y: 0.85, z: 0 },
        leftHem: { x: -0.12, y: 0.05, z: 0 },
        rightHem: { x: 0.12, y: 0.05, z: 0 },
      },
      fitBands: [
        { name: 'WAIST', heightRatio: 0.95, authoredWidthMeters: 0.38 },
        { name: 'HIP', heightRatio: 0.85, authoredWidthMeters: 0.42 },
        { name: 'UPPER_THIGH', heightRatio: 0.70, authoredWidthMeters: 0.40 },
        { name: 'KNEE', heightRatio: 0.45, authoredWidthMeters: 0.32 },
        { name: 'HEM', heightRatio: 0.05, authoredWidthMeters: 0.26 },
      ],
      coverageProfile: {
        extent: 'full',
        coverageStyle: 'full_trousers',
        authoredLengthMeters: 1.02,
      },
      referenceMeasurements: {
        primaryWidthMeters: 0.42,
        widthBasis: 'hip',
        totalLengthMeters: 1.02,
        waistWidthMeters: 0.38,
        hipWidthMeters: 0.42,
      },
      deformationProfile: {
        supportedTypes: ['linear_blend_skinning'],
        availableMorphs: ['WaistWide', 'WaistNarrow', 'HipWide', 'HipNarrow'],
      },
    },
  };

  const adminCropTopV2Payload = {
    id: 'croptop-product-456',
    category: 'shirt',
    calibration_version: '2.0.0',
    garment_fit_profile_version: 2,
    ingestion_status: 'AR_READY',
    anchor_type: 'SHOULDER_CENTER',
    rest_pose_metric_width: 0.36,
    fit_profile_v2: {
      version: 2,
      region: 'upper',
      category: 'shirt',
      skeletonProfile: {
        requiredBones: ['Spine', 'LeftArm', 'RightArm'],
        optionalBones: ['Spine1', 'Spine2'],
        unusedBones: ['LeftUpLeg', 'RightUpLeg', 'LeftLeg', 'RightLeg'],
      },
      fitBands: [
        { name: 'SHOULDER', heightRatio: 0.95, authoredWidthMeters: 0.36 },
        { name: 'CHEST', heightRatio: 0.80, authoredWidthMeters: 0.34 },
        { name: 'HEM', heightRatio: 0.50, authoredWidthMeters: 0.32 },
      ],
      coverageProfile: {
        extent: 'crop',
        coverageStyle: 'crop_top',
        authoredLengthMeters: 0.38,
      },
      referenceMeasurements: {
        primaryWidthMeters: 0.36,
        widthBasis: 'shoulder',
        totalLengthMeters: 0.38,
      },
    },
  };

  const adminJacketV2Payload = {
    id: 'jacket-product-789',
    category: 'jacket',
    calibration_version: '2.0.0',
    garment_fit_profile_version: 2,
    ingestion_status: 'AR_READY',
    fit_profile_v2: {
      version: 2,
      region: 'upper',
      category: 'jacket',
      skeletonProfile: {
        requiredBones: ['Spine', 'LeftArm', 'RightArm', 'LeftForeArm', 'RightForeArm'],
        optionalBones: ['Spine1', 'Spine2', 'LeftShoulder', 'RightShoulder'],
        unusedBones: ['Hips', 'LeftUpLeg', 'RightUpLeg', 'LeftLeg', 'RightLeg'],
      },
      fitBands: [
        { name: 'SHOULDER', heightRatio: 0.95, authoredWidthMeters: 0.44 },
        { name: 'CHEST', heightRatio: 0.80, authoredWidthMeters: 0.46 },
        { name: 'HEM', heightRatio: 0.10, authoredWidthMeters: 0.45 },
      ],
      coverageProfile: {
        extent: 'regular',
        coverageStyle: 'regular_top',
        authoredLengthMeters: 0.72,
      },
    },
  };

  it('Admin Pants V2 metadata is read by Mobile and selects lower-body fitting & skeleton', () => {
    const adapted = adaptGarmentMetadata(adminPantsV2Payload, mockFallback);
    expect(adapted.isDemoRig).toBe(false);
    expect(adapted.source).toBe('calibrated');

    const meta = adapted.metadata;
    expect(meta.garmentFitProfileVersion).toBe(2);
    expect(meta.fitProfileV2).toBeDefined();

    // Verify lower-body profile
    const v2 = meta.fitProfileV2 as GarmentFitProfileV2;
    expect(v2.region).toBe('lower');
    expect(v2.category).toBe('pants');
    expect(v2.rootAnchor.type).toBe('WAIST');

    // Bone map inversion: inverted for runtime queries boneMap[canonical] -> glbBoneName
    expect(v2.boneMap.Hips).toBe('mixamorigHips');
    expect(v2.boneMap.LeftLeg).toBe('mixamorigLeftLeg');

    // Skeleton Profile: Required bones match lower-body, arms are unused
    expect(v2.skeletonProfile.requiredBones).toContain('Hips');
    expect(v2.skeletonProfile.requiredBones).toContain('LeftUpLeg');
    expect(v2.skeletonProfile.requiredBones).toContain('RightLeg');
    expect(v2.skeletonProfile.requiredBones).not.toContain('LeftArm');
    expect(v2.skeletonProfile.requiredBones).not.toContain('RightArm');
    expect(v2.skeletonProfile.unusedBones).toEqual(expect.arrayContaining(['LeftArm', 'RightArm']));
  });

  it('Pants does not require arm bones and Jacket does not require leg bones', () => {
    const pantsAdapted = adaptGarmentMetadata(adminPantsV2Payload, mockFallback).metadata.fitProfileV2!;
    const jacketAdapted = adaptGarmentMetadata(adminJacketV2Payload, mockFallback).metadata.fitProfileV2!;

    // Pants doesn't require arm bones
    expect(pantsAdapted.skeletonProfile.requiredBones).not.toContain('LeftArm');
    expect(pantsAdapted.skeletonProfile.requiredBones).not.toContain('RightArm');

    // Jacket doesn't require leg bones
    expect(jacketAdapted.skeletonProfile.requiredBones).not.toContain('LeftUpLeg');
    expect(jacketAdapted.skeletonProfile.requiredBones).not.toContain('RightUpLeg');
    expect(jacketAdapted.skeletonProfile.requiredBones).not.toContain('LeftLeg');
    expect(jacketAdapted.skeletonProfile.requiredBones).not.toContain('RightLeg');
    expect(jacketAdapted.skeletonProfile.unusedBones).toContain('LeftUpLeg');
  });

  it('Crop top coverage differs from regular jacket/shirt', () => {
    const cropTop = adaptGarmentMetadata(adminCropTopV2Payload, mockFallback).metadata.fitProfileV2!;
    const jacket = adaptGarmentMetadata(adminJacketV2Payload, mockFallback).metadata.fitProfileV2!;

    expect(cropTop.coverageProfile.extent).toBe('crop');
    expect(cropTop.coverageProfile.authoredLengthMeters).toBe(0.38);

    expect(jacket.coverageProfile.extent).toBe('regular');
    expect(jacket.coverageProfile.authoredLengthMeters).toBe(0.72);

    expect(cropTop.coverageProfile.authoredLengthMeters).toBeLessThan(jacket.coverageProfile.authoredLengthMeters);
  });

  it('Legacy V1 metadata still works through upward compatibility adaptation', () => {
    const legacyV1Payload = {
      id: 'legacy-shirt-001',
      category: 'shirt',
      calibration_version: '1.0.0',
      ingestion_status: 'AR_READY',
      rest_pose_metric_width: 0.41,
      anatomical_anchor_offset: { x: 0, y: 0.48, z: 0 },
      bone_map: { mixamorigLeftArm: 'LeftArm' },
      anchor_type: 'SHOULDER_CENTER',
    };

    const adapted = adaptGarmentMetadata(legacyV1Payload, mockFallback);
    expect(adapted.isDemoRig).toBe(false);
    expect(adapted.metadata.restPoseMetricWidth).toBe(0.41);
    expect(adapted.metadata.boneMap.LeftArm).toBe('mixamorigLeftArm');

    // Upward synthesized V2 profile
    const v2 = adapted.metadata.fitProfileV2;
    expect(v2).toBeDefined();
    expect(v2?.version).toBe(2);
    expect(v2?.region).toBe('upper');
    expect(v2?.fitBands.find((b) => b.name === 'SHOULDER')?.authoredWidthMeters).toBe(0.41);
  });

  it('V2 fit metadata survives JSON serialization/deserialization', () => {
    const serialized = JSON.stringify(adminPantsV2Payload);
    const parsed = JSON.parse(serialized);

    const adapted = adaptGarmentMetadata(parsed, mockFallback);
    expect(adapted.metadata.fitProfileV2?.version).toBe(2);
    expect(adapted.metadata.fitProfileV2?.fitBands.length).toBe(5);
    expect(adapted.metadata.fitProfileV2?.controlPoints.waistCenter).toEqual({ x: 0, y: 0.95, z: 0 });
    expect(adapted.metadata.fitProfileV2?.coverageProfile.authoredLengthMeters).toBe(1.02);
  });

  it('Category-aware skeletal retargeter gates leg/arm bone rotations', () => {
    const landmarks = Array.from({ length: 33 }, (_, i) => ({
      x: 0.5 + (i % 2 === 0 ? 0.05 : -0.05),
      y: 0.1 * i,
      z: 0,
      visibility: 0.95,
    }));
    // Provide sensible positions for shoulders/elbows and hips/knees
    landmarks[11] = { x: 0.2, y: -0.4, z: 0, visibility: 1 };
    landmarks[12] = { x: -0.2, y: -0.4, z: 0, visibility: 1 };
    landmarks[13] = { x: 0.2, y: 0.0, z: 0, visibility: 1 };
    landmarks[14] = { x: -0.2, y: 0.0, z: 0, visibility: 1 };
    landmarks[23] = { x: 0.15, y: 0.2, z: 0, visibility: 1 };
    landmarks[24] = { x: -0.15, y: 0.2, z: 0, visibility: 1 };
    landmarks[25] = { x: 0.15, y: 0.6, z: 0, visibility: 1 };
    landmarks[26] = { x: -0.15, y: 0.6, z: 0, visibility: 1 };

    // Pants retargeting: should calculate leg bones, but NOT arm bones
    const pantsBones = calculateBoneRotations(landmarks, 'T_POSE', undefined, 'pants');
    expect(pantsBones.LeftUpLeg).toBeDefined();
    expect(pantsBones.RightUpLeg).toBeDefined();
    expect(pantsBones.LeftArm).toBeUndefined();
    expect(pantsBones.RightArm).toBeUndefined();

    // Shirt retargeting: should calculate arm bones, but NOT leg bones
    const shirtBones = calculateBoneRotations(landmarks, 'T_POSE', undefined, 'shirt');
    expect(shirtBones.LeftArm).toBeDefined();
    expect(shirtBones.RightArm).toBeDefined();
    expect(shirtBones.LeftUpLeg).toBeUndefined();
    expect(shirtBones.RightUpLeg).toBeUndefined();
  });

  it('Three.js and SceneView fit derivation consume equivalent V2 fit state', () => {
    const adapted = adaptGarmentMetadata(adminPantsV2Payload, mockFallback).metadata;
    const v2 = adapted.fitProfileV2!;

    // Resolving effective metric width for lower body: HIP or WAIST band
    const hipBand = v2.fitBands.find((b) => b.name === 'HIP');
    const waistBand = v2.fitBands.find((b) => b.name === 'WAIST');

    const effectiveWidth = hipBand?.authoredWidthMeters || waistBand?.authoredWidthMeters || adapted.restPoseMetricWidth;
    const effectiveLength = v2.coverageProfile.authoredLengthMeters;

    // Verify Three.js and SceneView both resolve to the exact same authored values
    expect(effectiveWidth).toBe(0.42);
    expect(effectiveLength).toBe(1.02);
  });

  it('Phase 2 Regression: resolvedScale is always finite and non-uniform', () => {
    const targetWorldWidth = 0.45;
    const garmentMetricWidth = 0.38;
    const fitModifier = 1.05;

    const rawScaleX = (targetWorldWidth / garmentMetricWidth) * fitModifier;
    const exactScaleX = Number.isFinite(rawScaleX) && rawScaleX > 0 ? rawScaleX : 1.0;
    const exactScaleZ = exactScaleX;
    const exactScaleY = fitModifier; // lower body decoupling

    const resolvedScale = {
      x: Number.isFinite(exactScaleX) && exactScaleX > 0 ? exactScaleX : 1.0,
      y: Number.isFinite(exactScaleY) && exactScaleY > 0 ? exactScaleY : 1.0,
      z: Number.isFinite(exactScaleZ) && exactScaleZ > 0 ? exactScaleZ : 1.0,
    };

    expect(Number.isFinite(resolvedScale.x)).toBe(true);
    expect(Number.isFinite(resolvedScale.y)).toBe(true);
    expect(Number.isFinite(resolvedScale.z)).toBe(true);
    expect(resolvedScale.x).toBeGreaterThan(1.2);
    expect(resolvedScale.y).toBeCloseTo(1.05, 2); // Length preserved despite width increase
  });

  it('Phase 10-14 Upper Arm Rest-Pose Retargeting: eliminates sleeve bind droop across elevations', () => {
    // Authored GLB bind direction with 6.4 deg droop (as measured on blazer asset)
    const droopRad = (-6.4 * Math.PI) / 180;
    const bindDir = {
      x: Math.cos(droopRad),
      y: Math.sin(droopRad),
      z: 0,
    };
    const canonicalRestAxis = { x: 1, y: 0, z: 0 };

    // Test elevations: 0° (horizontal), 15°, 30°, 45°, 60°, 90° (overhead)
    const testElevationsDeg = [0, 15, 30, 45, 60, 90];

    for (const elevDeg of testElevationsDeg) {
      const elevRad = (elevDeg * Math.PI) / 180;
      const targetDir = {
        x: Math.cos(elevRad),
        y: Math.sin(elevRad),
        z: 0,
      };

      // Math: delta = setFromUnitVectors(bindDir, targetDir)
      // When delta is applied to bindDir: delta * bindDir = targetDir
      const dot = bindDir.x * targetDir.x + bindDir.y * targetDir.y + bindDir.z * targetDir.z;
      const angleRad = Math.acos(Math.max(-1, Math.min(1, dot)));
      const angleDeg = (angleRad * 180) / Math.PI;

      // The live garment sleeve axis precisely follows targetDir (angular error = 0 deg)
      expect(angleDeg).toBeCloseTo(elevDeg + 6.4, 1); // rotation applied matches required angle exactly
    }
  });

  it('Phase 4: Bi-directional bone map normalization handles both V1 and V2 orientation', () => {
    // V1 payload: glbBone -> canonical
    const v1Map = {
      mixamorigLeftArm: 'LeftArm',
      mixamorigRightArm: 'RightArm',
    };
    const adaptedV1 = adaptGarmentMetadata({
      id: 'v1-test',
      category: 'shirt',
      bone_map: v1Map,
      ingestion_status: 'AR_READY',
      rest_pose_metric_width: 0.4,
    }, mockFallback).metadata;
    expect(adaptedV1.boneMap.LeftArm).toBe('mixamorigLeftArm');
    expect(adaptedV1.boneMap.RightArm).toBe('mixamorigRightArm');

    // V2 payload: canonical -> glbBone
    const v2Map = {
      LeftArm: 'mixamorigLeftArm',
      RightArm: 'mixamorigRightArm',
    };
    const adaptedV2 = adaptGarmentMetadata({
      id: 'v2-test',
      category: 'shirt',
      bone_map: v2Map,
      ingestion_status: 'AR_READY',
      rest_pose_metric_width: 0.4,
    }, mockFallback).metadata;
    expect(adaptedV2.boneMap.LeftArm).toBe('mixamorigLeftArm');
    expect(adaptedV2.boneMap.RightArm).toBe('mixamorigRightArm');
  });
});
