-- ARAssets.jsx (admin-dashboard) has always written arStatus, arAlignPoints,
-- and arAlignments as if they were real columns on products. None of them
-- exist under any name -- confirmed via information_schema before this
-- migration -- so every AR status toggle and every "Save & Verify Points"
-- click has been throwing on an unknown-column UPDATE with no user-visible
-- error surfaced by the try/catch wrapping it. This has never worked.
--
-- Chosen over three real columns: AR metadata (status, alignment points,
-- alignment verification state) is admin-configuration for a still-evolving
-- feature, read/written from exactly one screen, with no need for it to be
-- indexed, filtered, or joined on at the SQL level. A jsonb blob keeps
-- schema churn contained to this migration instead of a new ALTER TABLE
-- each time the AR config shape grows.
--
-- Shape written by admin-dashboard (camelCase, converted to/from snake_case
-- at the toCamel/toSnake boundary like every other column):
--   { status: 'Active' | 'Disabled',
--     alignPoints: { shoulderL, shoulderR, waist, hips } (each "x, y, z" string),
--     alignments: 'Pending' | 'Verified' | 'Failed' }

ALTER TABLE public.products ADD COLUMN IF NOT EXISTS ar_data jsonb NOT NULL DEFAULT '{}'::jsonb;
